//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public string Employee_ID { get; set; }
        public string Rating1 { get; set; }
        public int Shift_Id { get; set; }
        public bool Shift_Approved { get; set; }
        public int Shift_In_Day { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Shifts_In_Days Shifts_In_Days { get; set; }
    }
}
