//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShiftsEntities : DbContext
    {
        public ShiftsEntities()
            : base("name=ShiftsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Business> Business { get; set; }
        public virtual DbSet<Constraints> Constraints { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employee_Roles> Employee_Roles { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<Shift_Employees> Shift_Employees { get; set; }
        public virtual DbSet<Shifts> Shifts { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
