//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift_Employees
    {
        public int Business_Id { get; set; }
        public int Departments_Id { get; set; }
        public int Role_Id { get; set; }
        public int Shift_ID { get; set; }
        public int Number_Of_Shift_Employees { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Employee_Roles Employee_Roles { get; set; }
        public virtual Shifts Shifts { get; set; }
    }
}
