//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShiftEntities : DbContext
    {
        public ShiftEntities()
            : base("name=ShiftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assigning> Assigning { get; set; }
        public virtual DbSet<Business> Business { get; set; }
        public virtual DbSet<Constraints> Constraints { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employee_Roles> Employee_Roles { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<Satisfaction_Status> Satisfaction_Status { get; set; }
        public virtual DbSet<Shift_Employees> Shift_Employees { get; set; }
        public virtual DbSet<Shifts> Shifts { get; set; }
        public virtual DbSet<Shifts_In_Days> Shifts_In_Days { get; set; }
    
        public virtual int add_employee_in_department(string employee_id, Nullable<int> department_id)
        {
            var employee_idParameter = employee_id != null ?
                new ObjectParameter("employee_id", employee_id) :
                new ObjectParameter("employee_id", typeof(string));
    
            var department_idParameter = department_id.HasValue ?
                new ObjectParameter("department_id", department_id) :
                new ObjectParameter("department_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_employee_in_department", employee_idParameter, department_idParameter);
        }
    }
}
